Compilation of features:
Project-Planner/backend pull request #7
Opened 2021-07-05 11:03 UTC by llambdaa

- Transformed XML structs (+ base value pair struct)
- Moved database constructor
- Refactored database
- Implemented basic database functionality (logic + serialization)
- Made utility functions (file and parse)

2021-07-05 18:09 UTC, 4kills requested changes
Generell: Sehr gut für dein ersten Go code, bin sehr zufrieden, auch wenn es jetzt nach sehr viel aussieht, aber ist oft meckern auf hohem niveau. 
Auf jeden Fall noch:
**Tests schreiben**, bevor ich dich auf meinem server im file system rumpfuschen lass, will ich sehen, dass es funktioniert :P

2021-07-05 18:09 UTC, 4kills commented on config.yaml
> +calendar_dir: "/home/llambdaa/Downloads/xmldb/calendars"
warum hast du dafür überall einezlne, customizable folder gemacht? Mir wäre es ehrlich gesagt lieber, wenn der user (also ich) nicht so ein level an detaillgrad habe. Wenn ich eine herkömmliche Datenbank hätte (mongo, mysql, ...) würde ich dem ja auch nur ein folder geben und nicht für jeden table entscheiden, wo der jetzt auf meinem system liegt. Also am liebsten wäre mir schon ein db_root_dir wovon du einfach die relativen pfade ./auth, ./user, ./calendar etc. nimmst. Könntest es auch db_dir nennen (dann ist es coherent mit html_dir

2021-07-05 18:09 UTC, 4kills commented on main.go
> +	db.AddUser("Lukas", "bla")
also tests haben natürlich in der main nichts zu tun :P Das muss rausgelöscht werden bevor es gemerged wird. Wenn du dir proven willst, dass es funktioniert, schreib tests! Das brauchen wir sowieso. Zumindest ein paar ganz rudimentäre tests will ich gerne sehen bevor ich dich da in dem file system von meinem server rumbasteln lass :P

2021-07-05 18:09 UTC, 4kills commented on main.go
> +	db, err := xmldb.NewDatabase(c.DBConfig)
Mir ist bisschen unklar, warum du das umbenannt hast? In go hat man häufig, dass man einfach nur ein New hat, weil das package ja xmldb heißt. Also "new xml db" -> xmldb.New(). Aber das ist jetzt nicht so schlimm. Lösch dann abera uch die New-Methode die ich schon gemacht hab

2021-07-05 18:09 UTC, 4kills commented on model/attribute.go
> +type Attribute struct {
Ich finde sehr sehr sehr gut, dass du "Attribute" auslagerst. Ich denke den xml.Name benötigst du zum querien in der file??? Oder wozu? Ansonsten hätte ich noch gern, dass das Attribute noch das Text attribute hat, wie in den bisherigen strukturen der fall war. Außerdem wäre es besser, "Value" zu "Val" umzubenennen, da du sonst überall meinen Code ändern musst, was nicht so unbedingt nötig wäre. Lieber den neuen Code von Value auf Val ändern anstatt die ganze bestehende Code-Base

2021-07-05 18:09 UTC, 4kills commented on model/auth.go
> +func NewAuth() Auth {
das würde man in Go so nicht machen, wenn die Funktion nichts macht, sondern einfach Auth{} an der fraglichen Stelle im Code anwenden.

2021-07-05 18:09 UTC, 4kills commented on model/auth.go
> +}
Diese Methode muss man zu "String()" umbenennen, damit sie das [Stringer Interface](https://golang.org/pkg/fmt/#Stringer) erfüllt, und somit in fmt.Println(..) und log.Println() richtig gepassed werden kann. Das "toString" äquivalent in go heißt also "String()".

2021-07-05 18:09 UTC, 4kills commented on model/user.go
> +	return string(parsed)
Das selbe heir ToString() zu String() umbenennen

2021-07-05 18:09 UTC, 4kills commented on web/auth.go
> +	if err := bcrypt.CompareHashAndPassword([]byte(l.Hash.Value), []byte(pw)); err != nil {
Wie gesagt du kannst es jetzt überall zu Value umbenennen wenn du wirklich willst, aber ich würde es leiber haben dass es überall Val heißt, weil ich jetzt grade auch noch code schreibe der das Val nennt. Ist immer gut das backwads compatible zu machen und nicht was zu ändern in der ganzen code base was nicht geändert werden muss

2021-07-05 18:09 UTC, 4kills commented on config.yaml
> +calendar_dir: "/home/llambdaa/Downloads/xmldb/calendars"
Also ich würde das wirklich gerne als Implementationsdetail belassen, geht den user ja nichts an wie der Ordner aufgebaut wird, der er dem programm zur verfügung stellt

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +type Database struct {
ich glaub database muss nicht unbedingt public sein -> klein schreiben. Außerdem sollte der comment darüber in Go so aufgebaut sein: // database implements the web.Database interface. DAs erleichtert Go die zuordnung der kommentare zu der struct und ist sozusagen wie java doc

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +	ensureDir(config.CalendarDir)
Genau hier würde ich jetzt eben hergehen und einfach die subdirectories /auth, /user, ... von config.db_root_dir verwenden

2021-07-05 18:09 UTC, 4kills commented on xmldb/dbconfig.go
> +	CacheSize int `yaml:"cache_size"`
Der wert sollte in byte angegeben werden, nicht in anzahl elementen. Weiß ich doch als dummer sys admin nicht, wie groß die sind :P

2021-07-05 18:09 UTC, 4kills commented on xmldb/file.go
> +}
Hier ist die frage, gibt es nur ein error wenn es nicht gefunden wurde, oder könnte auch permission denied sein ? IN letzterem falle wäre der methodennamen misleading. 
Aber ich denke das ist okay als utility funktion. Aber wäre gut wenn du in den doc string drüber noch includest: returns also false, if another error occurs, like if the program doesn't have the permission to access the path

2021-07-05 18:09 UTC, 4kills commented on xmldb/file.go
> +}
error reporting, falls ein fehler auftritt, bitte. 
Außerdem würde ich das nicht so low, level machen, benutz einfach die funktion os.WriteFile, die macht genau das, was du hier willst, und so musst du nur einen einzigen error checken / returnen. Theoretisch müsstest du nämlich für jeden dieser 4 calls in dem if die errors checken. Außerdem schreibt writestring nicht automatisch alles, sondern muss ggf wiederholt gecalled werden. Benutz lieber `os.WriteFile`

2021-07-05 18:09 UTC, 4kills commented on xmldb/file.go
> +}
Theoretisch kannst du dir diese ganze funktion sparen, wenn du setFile verwendest mit os.WriteFile, da os.WriteFile das file erstellt, falls es nicht vorher da war. Das wäre eigentlich ganz gut, um die code base möglichst klein zu halten

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +	var authPath = fmt.Sprintf("%s/%s", config.AuthDir, "/auth.xml")
uhm das erzeugt einen doppelten `/` , also angenommen config.AuthDir = /var/etc, dann ergibt das `/var/etc//auth.xml`. Falls config.AuthDir = /var/etc/ erzeugt es sogar einen triple slash. Das ist noch ein Grund das selbst zu machen und nur das root directory zu nehmen. Dann kann das auf fehler überprüft werden und man selbst kann die ordner rumfuhrwerken wie man will und muss nicht für jeden folder nochmal auf eingabefehler des users überprüfen

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +	}
Das ist gut gemacht

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +		var matching, _ = regexp.MatchString(".+\\.xml$", name)
In go kann man strings auch mit backticks `  angeben und dann werden sie wirklich buchstäblich (auch mit newline etc genommen). Nur so als Info am Rande. Das könnte dann so aussehen: 
```suggestion
		var matching, _ = regexp.MatchString(`.+\.xml$`, name)
```

2021-07-05 18:09 UTC, 4kills commented on xmldb/parse.go
> +}
Ich würde die errors, die hier entstehen können lieber returnen :P Musst ja nichts handeln einfach
if err != nil {
    return err
} 
Das ist so the way für error handling in go. Finde ich besser als exceptions

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +			users[uuid] = user
Ich würde mir hier nicht die uuid aus dem dateinamen ziehen, da die methode prone für off by one errors ist und du ja eh den user passed, und dann die uuid auch einfach aus user.Name (oder so) ziehen kannst. Natürlich wäre es sogar noch mehr sahne, wenn du dann checken würdest, ob der file name tatsächlich zum username passt, aber muss nicht sein. Das kannst auch so lassen wie es jetzt ist. Damit wäre ich fine. Just food for thought.

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +	if _, exists := db.auth[name]; !exists {
hieraus bitte einmal ein guard statement machen, dann kann man sich den indent sparen. Btw Shift + Alt + L auto formatted den code in golang (wie in jedem jetbrains produkt).

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +func (db Database) AddUser(name, hash string) error {
Bei den ganzen exportierten methoden bitte einen aussagekräftigen doc string und da erwähnen was die methode macht, also zum beispiel auch, dass sie checkt, ob der name schon vorhanden ist und einen error wirft, falls ja. Dann ist die impl klar. Manche AddUser überschreiben sonst einfach

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +	var auth = make(map[string]model.Login)
In go würde man das eher so schreiben. Kenne niemand der das so mit `var name =` macht. Aber kannst auch gern so lassen. Ist personel preference, aber gibt mir immer so JS vibes. Wollte es nur gesagt haben 
```suggestion
	auth := make(map[string]model.Login)
```

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +		var uuid = uuid.New().String()
die variable so zu nennen wie ein package ist eher suboptimal. Weil das dann collided und zu amiguity führt. nenn die variable lieber id oder so

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +		var path = fmt.Sprintf("%s/%s.xml", db.config.UserDir, uuid)
so würde ich das nur sehr ungern machen. Ich würde die uuid nicht in den namen reinpacken. Der username ist eigentlich uuid genug, weil der unique sein muss. Die uuid wird wahrscheinlich niemals verwendet. Würde das mit der uuid lieber ganz weg lassen. Das macht dir nur mehr aufwand, wenn du dann später die dateien öffnen und bearbeiten musst, denke ich.

2021-07-05 18:09 UTC, 4kills commented on model/user.go
> +	return string(parsed)
Du kannst die methode btw auch refactoren mit intellij. dazu einfach rechtsclick -> refactor -> rename. Dann veräandert das auch alle anwendungen davon.

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +		var logins = []model.Login{}
das ist auch eher unüblich das so zu machen. Eher 
```suggestion
		var logins []model.Login
```
Aber noch viel besser wäre 
```suggestion
		logins := make([]model.Login, len(db.auth)) 
```
Denn du kennst doch schon die länge die das slice haben muss. Wenn du das mit append machst, dann wird ultra häufig neuer speicherplatz alloziert, was natürlich slow ist

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +		}
Würde das eher so machen (effizienter, da länge bekannt). Kannst dann später immer noch was ran-appenden. Außerdem macht man häufig nur ein v in solchen loops weil ja klar ist dass das jetzt die value ist. ABer kann man auch value nennen, wollte nur go konventionen näher bringen. 
```suggestion
		for i, v := range db.auth {
			logins[i] = v
		}
```

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +		path = fmt.Sprintf("%s/%s", db.config.AuthDir, db.config.AuthSubpath)
mir ist die notwendigkeit des subpaths nicht so ganz einleuchtend. Aber heir auch wieder das probblem des doppelten `/` ggf. Das niederschreiben sollte man btw noch in eine neue methode auslagern und mit `go write` callen oder so. Aber das machst du ja glaube ich grad

2021-07-05 18:09 UTC, 4kills commented on xmldb/database.go
> +	}
Die methode gefällt mir eigentlich gut. Finde super, dass du model.ErrNotFound verwendet hast. In idiomatic go würde man die methode eher so schreiben: 
```suggestion
	val, ok := db.auth[name]
	if !ok {
		return model.Login{}, model.ErrNotFound
	} 
	return val, nil 
```
Aber änder das nicht, das ist okay so

2021-07-08 12:55 UTC, llambdaa commented on xmldb/database.go
> +	}
Danke ;)

2021-07-12 11:15 UTC, 4kills commented
There are a lot of unhandled errors,  I will quickly fix that

2021-07-12 11:52 UTC, 4kills approved these changes
Haben es ja im Pair Programming gemerged und die anderen Problemchen wurden auch gelöst, also kann man das jetzt mergen

2021-07-12 11:53 UTC, merged